### ISSUE TITLE
Add and improve article metadata

### ISSUE THREAD

**Issue by wang-arthur** [Post45-Journal/Roadmap#9]
- [ ] Check Google Scholar meta tags (dupe of https://github.com/Post45-Journal/Projects/issues/12)
- [ ] Add Twitter card markup (we currently add these manually!) Related to https://github.com/Post45-Journal/Projects/issues/28
- [ ] For references/citations, follow [Initiative for Open Citations](https://i4oc.org/) and [CrossRef ](https://www.crossref.org/documentation/principles-practices/best-practices/)format & guidelines
- [ ] Register DOIs (contingent on #8)

**Comment by wang-arthur** [comment]
Resources
- https://www.crossref.org/documentation/principles-practices/
- https://docs.pkp.sfu.ca/getting-found-staying-found/en/
- https://schema.org/
